<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>Bowtie</Title>
    <Authors>Guuours</Authors>
    <Copyright>Copyright @ Guuours 2026</Copyright>
    <Version>0.0.1</Version>
    <PackageIcon>suit.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="suit.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
